status/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statuspage.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
]

statuspage/urls.py
from django.urls import path
from . import views

app_name = "statuspage"

urlpatterns = [
    path('', views.move),
    path('status/', views.status, name='status'),
]

story7/urls.py
from django.urls import path
from . import views

appname = "story7"

urlpatterns = [
    path('about/', views.aboutme, name='about'),
]

story8/urls.py
from django.urls import path
from . import views

appname = "story8"

urlpatterns = [
    path('book/', views.bookpage, name='book'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = "story9"

urlpatterns = [
    path('story9/', views.home, name='home'),
    path('story9/login', views.log_in, name='login'),
    path('story9/logout', views.log_out, name='logout'),
]

statuspage/models.py
from django.db import models

class Stat(models.Model):
    description = models.TextField(max_length=300)
    model_date = models.DateTimeField(auto_now_add=True)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

statuspage/forms.py
from django import forms
from .models import Stat

class Stat_Form(forms.Form):
    error = {
        'required' : 'This field is required'
    }
    desc_attr = {
        'name' : 'name_desc',
        'type' : 'text',
        'rows' : 8,
        'cols' : 50,
        'class' : 'form-control',
        'placeholder' : 'Write your mind..'
    }
    
    description = forms.CharField(label='',required=True, widget=forms.Textarea(attrs=desc_attr), max_length=300)

    class Meta:
        model = Stat
        field = ['description']

statuspage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Stat
from .forms import Stat_Form
from django.utils import timezone
import datetime

def status(request):
    display_form = Stat_Form()
    form = Stat_Form(request.POST or None)
    if (request.method == "POST" and form.is_valid()):
        server_time = datetime.datetime.now()
        desc = Stat(description=form['description'].value(), model_date=server_time)
        desc.save()
    status_list = Stat.objects.all().order_by('-model_date')
    response = {
        'list' : status_list,
        'server_time' : datetime.datetime.now(),
        'form' : display_form,
    }
    return render(request, "statuspage.html", response)

def move(request):
    return HttpResponseRedirect('/status')

story7/views.py
from django.shortcuts import render, redirect

def aboutme(request):
    return render(request, 'aboutme.html')

story8/views.py
from django.shortcuts import render

def bookpage(request):
    return render(request, 'bookpage.html')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

def home(request):
    message_error = "Your account and / or password is incorrect, please try again."
    user = request.user
    if(user.is_authenticated):
        return redirect('story9:login')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('story9:login')
    else:
        form = AuthenticationForm()
    return render(request, 'halamanlogin.html', {'form': form , 'error': message_error})

def log_in(request):
    return render(request, 'dashboard.html')

def log_out(request):
    logout(request)
    return redirect('story9:home')

statuspage/templates/statuspage.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/statuspage.css' %}">
{% endblock %}

{% block content %}

<div class="first-container container-fluid">
    <div class="form-container container-fluid">
        <form method="POST" action="/status/">
            <h1 class="status-judul text-center">Write your status!</h1>
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="button-submit" value="Submit" name='name_submit' id='id_submit'/>
        </form>
    </div>
</div>

<div class="status-container container-fluid">
    {% for j in list %}
    <div class="message-sheet">
        <div class="row">
            <div class="col-md-10">
                <p class="message"> {{ j.description }} </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                <p class="date-message">{{ j.model_date }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

{% block script %}{% endblock %}

story7/templates/aboutme.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/aboutme.css' %}">
<script src="{% static 'js/aboutme.js' %}"></script>
{% endblock %}

{% block content %}
<div class="check row">
    <div class="custom-control custom-switch ml-auto" id="change">
        <input type="checkbox" class="custom-control-input" id="custom" onchange="change()">
        <label class="custom-control-label" for="custom" id="toggle">Change Theme</label>
    </div>
</div>

<h4 class="judul text-center">Hello, I’m Shannia Dwi Melianti and <br/> I’m interesting in design and technologies.</h4>

<div class="container">
    <div class="row">
        <div class="profile col-md-4">
            <img src="../static/img/image.jpg" alt="profile picture" class="img-photo">
            <div class="data-profile">
                <h6 class="text-center">Shannia Dwi Melianti</h6>
                <h6 class="text-center">Tangerang, 12 Maret 2000</h6>
                <h6 class="text-center">Loving art and music.</h4>
            </div>
        </div>
        <div class="about col-sm-7">
            <div id="accordion">
                <h3 class="data-hover">Activities</h3>
                    <div class='data-acd'>
                        <p>Study in Fasilkom UI.</p>
                        <p>Singing and make art stuff.</p>
                        <p>Become a part of Puspa Swara.</p>
                    </div>
                <h3 class="data-hover">Experiences</h3>
                    <div class="data-acd">
                        <p>2016 Secretary at Voseuth Choir</p>
                        <p>2019 Decoration Division Staff at UI Ethnovaganza 2019</p>
                    </div>
                <h3 class="data-hover">Achievements</h3>
                    <div class="data-acd">
                        <p>2015 3rd Place in Jabodetabek Vocal Grup Competition</p>
                        <p>2018 1st Best Student at Natural Science Major SMAN 7 Tangerang Selatan</p>
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}{% endblock %}

story8/templates/bookpage.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/story8.css' %}">
<title>Search</title>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1 class="judul text-center">Place to find the best books for you.</h1>
    <div class="flex-lg-column justify-content-center">
        <input type="text" class="form-control" id="search" placeholder="Search books or type the title here..">
    </div>
    <table class="table justify-content-center text-center">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Book Cover</th>
                <th scope="col">Book Title</th>
                <th scope="col">Author</th>
                <th scope="col">Publisher and Published Date</th>
            </tr>
        </thead>
        <tbody id="books"></tbody>
    </table>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/story8.js' %}"></script>
{% endblock %}

story9/templates/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<h2 class='selamat text-center'>Selamat datang, {{ user }}!</h2>
<button class="button text-center"><a href='{% url "story9:logout" %}'>Logout</a></button>

{% else %}
<h2 class='selamat text-center'>Eh, kamu belum login lho. Login dulu yuk!</h2>
<button class="button"><a href='{% url "story9:home" %}'>Login</a></button>
{% endif %}

{% endblock %}

{% block script %}{% endblock %}

story9/templates/halamanlogin.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/halamanlogin.css' %}">
{% endblock %}

{% block content %}
<h2 class="hello text-center">Welcome to my website!<br/>Login dulu yuk.</h2>
<div class='container-fluid text-center'>
    {% if form.errors %}
    {{error}}
    {% endif %}
    <form method="POST" action='/story9/'>
        {% csrf_token %}
        <label>Username : </label>
        <br/>
        {{ form.username }}
        <br/>
        <label>Password   : </label>
        <br/>
        {{ form.password }}
        <br/>
        <input type="submit" value="Login" class="button">
    </form>
</div>

{% endblock %}

{% block script %}{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=0.8">
        <title>Status Page</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        {% block styles %}{% endblock %}
    </head>
    <body style="background-color: rgb(220, 220, 220);">
        {% block content %}{% endblock %}
        <nav class="navbar navbar-expand-lg">
            <a class='navbar-brand' href="/">Shans'</a>
            <span class="navbar-dark">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#mainNav">
                    <span class="navbar-toggler-icon rounded-circle"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </span>
            <div class="collapse navbar-collapse" id="mainNav" >
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/status/">Status</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about/">About</a>
                    </li>
                </ul>
            </div>
        </nav>
        
        <footer class="footer text-center">
            <p>You write so beautifully!</p>
        </footer>
    </body>
    {% block script %}{% endblock %}
</html>